const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const f=require(path.join(process.env.EXTENSION_ROOT||path.join(__dirname,'..'),'comp-property-fields.js'));
for(const [raw,value] of [["24'6\"",24.5],['18 ft',18],['  ',null],['0',null],['24-30 ft',null],['24 m',null]])test(`clear height ${raw} keeps exact units`,()=>assert.equal(f.parse('clear_height_ft',raw).value,value));
test('office zero and commas retained; malformed/ranged values blocked',()=>{assert.deepEqual(f.parse('office_sf','0'),{value:0});assert.deepEqual(f.parse('office_sf','4,500'),{value:4500});for(const s of ['4,50','400-500','-1'])assert.ok(f.parse('office_sf',s).error);});
test('year/lease/loading constraints match confirmed contract',()=>{assert.ok(f.parse('year_built','2000s').error);assert.ok(f.parse('lease_area','0').error);assert.ok(f.parse('loading','x'.repeat(4001)).error);assert.equal(f.parse('loading','Grade-level only').value,'Grade-level only');});
test('feature flags retain true false and unknown',()=>{for(const k of f.flags){for(const [raw,value] of [['true',true],['false',false],['',null],[null,null]])assert.deepEqual(f.parse(k,raw),{value});assert.ok(f.parse(k,'unknown text').error);}});
test('office and height source parsed; power/rail proximity do not become confirmations',()=>{const r=f.fromScrape({yearBuilt:'1980',propertyFacts:{clearHeight:'24\'6"',officeSf:'4,500 SF',power:'200 amps',railLine:'Union Pacific',docks:'None'}});assert.equal(r.values.clear_height_ft,24.5);assert.equal(r.values.office_sf,4500);assert.equal(r.values.heavy_power,undefined);assert.equal(r.values.has_rail,undefined);assert.equal(r.values.has_truckwell_or_dock,undefined);assert.equal(r.unresolved.length,2);});
test('positive dock/truckwell is explicit access evidence; both absent needed for No',()=>{assert.equal(f.fromScrape({propertyFacts:{docks:'2 ext'}}).values.has_truckwell_or_dock,true);assert.equal(f.fromScrape({propertyFacts:{docks:'None',truckWells:'None'}}).values.has_truckwell_or_dock,false);assert.equal(f.fromScrape({propertyFacts:{docks:'0'}}).values.has_truckwell_or_dock,undefined);});
test('divisible source never allocates whole-source office/loading or feature flags',()=>{const r=f.fromScrape({yearBuilt:'1980',selectedSpace:{availableRange:{min:'5000',max:'10000'},availableSf:null},propertyFacts:{officeSf:'600',loading:'Docks: 10 ext',docks:'10 ext',heavyPower:'Yes'}});assert.deepEqual(r.values,{year_built:1980});assert.match(r.unresolved[0],/confirm/);});
test('invalid values report fields before any save payload can be accepted',()=>{const r=f.serialize({clear_height_ft:'0',office_sf:'bad',heavy_power:'bad',loading:'x'.repeat(4001)});assert.deepEqual(r.issues.map(i=>i.field),['clear_height_ft','office_sf','loading','heavy_power']);});

test('property types match current canonical list and normalize legacy Class C',()=>{assert.deepEqual(f.propertyTypes,['ISF','IOS','Class A','Class B','Vintage','Flex','Land','Cold Storage']);assert.deepEqual(f.normalizePropertyTypes('ISF;Class C, Vintage'),['ISF','Vintage']);});
